/**
 * tests/gen_safe_primes.cc
 *
 * Generates 100 safe prime PAIRS (p, q) using Module 7 BigIntOps
 * and saves them to json/safe_primes.json
 *
 * COMPILE:
 *   g++-13 -std=c++20 -Wall -Wextra -pthread \
 *       -I. -I./utils -I./crypto -I/usr/include \
 *       tests/gen_safe_primes.cc \
 *       utils/uav-error.cc \
 *       utils/uav-enum-strings.cc \
 *       utils/uav-time-utils.cc \
 *       utils/uav-string-utils.cc \
 *       utils/uav-byte-utils.cc \
 *       utils/uav-math-utils.cc \
 *       utils/uav-file-utils.cc \
 *       utils/uav-log-level.cc \
 *       utils/uav-log-sink.cc \
 *       utils/uav-logger.cc \
 *       utils/uav-csv-logger.cc \
 *       crypto/uav-bigint.cc \
 *       -o tests/gen_safe_primes
 *
 * RUN:
 *   cd scratch/uav-secure-fanet/
 *   ./tests/gen_safe_primes --count 100 --bits 64 --seed 42
 *   ./tests/gen_safe_primes --count 18  --bits 512 --seed 42
 */

#include "crypto/uav-bigint.h"
#include "crypto/uav-bigint-utils.h"
#include "utils/uav-logger.h"
#include "utils/uav-file-utils.h"
#include "utils/uav-string-utils.h"
#include "utils/uav-time-utils.h"

#include <iostream>
#include <string>
#include <vector>
#include <random>
#include <sstream>
#include <cstdlib>

using namespace uav::crypto;
using namespace uav;

// ---------------------------------------------------------------------------
// Simple CLI argument parser
// ---------------------------------------------------------------------------
struct Args {
    int         count   = 100;
    unsigned    bits    = 64;       // 64-bit for testing, 512 for production
    uint64_t    seed    = 42;
    std::string output  = "json/safe_primes.json";
};

Args ParseArgs(int argc, char* argv[]) {
    Args a;
    for (int i = 1; i < argc; ++i) {
        std::string arg(argv[i]);
        auto eq = arg.find('=');
        if (eq == std::string::npos) continue;
        std::string key = arg.substr(0, eq);
        std::string val = arg.substr(eq + 1);
        if      (key == "--count")  a.count  = std::stoi(val);
        else if (key == "--bits")   a.bits   = static_cast<unsigned>(std::stoul(val));
        else if (key == "--seed")   a.seed   = std::stoull(val);
        else if (key == "--output") a.output = val;
    }
    return a;
}

// ---------------------------------------------------------------------------
// JSON builder (no external dependency)
// ---------------------------------------------------------------------------
std::string BuildJson(
    const std::vector<std::pair<BigInt,BigInt>>& pairs,
    unsigned bits,
    uint64_t seed)
{
    std::ostringstream j;
    j << "{\n";
    j << "  \"_comment\": \"Safe prime pairs generated by Module 7 BigIntOps\",\n";
    j << "  \"bits\": " << bits << ",\n";
    j << "  \"seed\": " << seed << ",\n";
    j << "  \"count\": " << pairs.size() << ",\n";
    j << "  \"pairs\": [\n";

    for (std::size_t i = 0; i < pairs.size(); ++i) {
        const auto& [p, q] = pairs[i];
        j << "    {\n";
        j << "      \"index\": " << i << ",\n";
        j << "      \"p\": \"" << BigIntOps::ToDecString(p) << "\",\n";
        j << "      \"q\": \"" << BigIntOps::ToDecString(q) << "\",\n";
        j << "      \"x\": \"" << BigIntOps::ToDecString(BigIntOps::ComputeX(p)) << "\",\n";
        j << "      \"y\": \"" << BigIntOps::ToDecString(BigIntOps::ComputeY(q)) << "\",\n";
        j << "      \"p_bits\": " << (boost::multiprecision::msb(p) + 1) << ",\n";
        j << "      \"q_bits\": " << (boost::multiprecision::msb(q) + 1) << "\n";
        j << "    }";
        if (i + 1 < pairs.size()) j << ",";
        j << "\n";
    }

    j << "  ]\n";
    j << "}\n";
    return j.str();
}

// ---------------------------------------------------------------------------
// Verify a single pair
// ---------------------------------------------------------------------------
bool VerifyPair(const BigInt& p, const BigInt& q) {
    // p must be safe prime
    if (!BigIntOps::IsSafePrime(p)) return false;
    // q must be safe prime
    if (!BigIntOps::IsSafePrime(q)) return false;
    // p and q must be distinct
    if (p == q) return false;
    return true;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char* argv[]) {

    Args args = ParseArgs(argc, argv);

    // Suppress logger noise
    log::Logger::Instance().Initialize(
        "logs", log::LogLevel::WARN, false);

    std::cout << "========================================\n";
    std::cout << " Safe Prime Generator — Module 7\n";
    std::cout << " UAV Secure FANET / NS-3.43\n";
    std::cout << "========================================\n\n";
    std::cout << " Count  : " << args.count  << " pairs\n";
    std::cout << " Bits   : " << args.bits   << " per prime\n";
    std::cout << " Seed   : " << args.seed   << "\n";
    std::cout << " Output : " << args.output << "\n\n";

    // RNG seeded deterministically
    std::mt19937_64 rng(args.seed);

    std::vector<std::pair<BigInt,BigInt>> pairs;
    pairs.reserve(static_cast<std::size_t>(args.count));

    auto wall_start = utils::TimeUtils::NowSteadyMicros();

    for (int i = 0; i < args.count; ++i) {

        auto iter_start = utils::TimeUtils::NowSteadyMicros();

        // Generate two independent safe primes per pair
        BigInt p = BigIntOps::GenerateSafePrime(args.bits, rng);
        BigInt q = BigIntOps::GenerateSafePrime(args.bits, rng);

        // Ensure p != q
        while (p == q) {
            q = BigIntOps::GenerateSafePrime(args.bits, rng);
        }

        auto iter_end  = utils::TimeUtils::NowSteadyMicros();
        auto iter_ms   = (iter_end - iter_start) / 1000;

        // Verify
        bool ok = VerifyPair(p, q);

        std::cout << "  [" << std::setw(3) << (i + 1) << "/" << args.count << "] "
                  << "p=" << BigIntOps::ToDecString(p).substr(0, 20) << "... "
                  << "q=" << BigIntOps::ToDecString(q).substr(0, 20) << "... "
                  << iter_ms << "ms "
                  << (ok ? "[OK]" : "[FAIL]")
                  << "\n";

        if (!ok) {
            std::cerr << "ERROR: Pair " << i
                      << " failed verification!\n";
            return EXIT_FAILURE;
        }

        pairs.emplace_back(std::move(p), std::move(q));
    }

    auto wall_end = utils::TimeUtils::NowSteadyMicros();
    auto total_ms = (wall_end - wall_start) / 1000;

    std::cout << "\n========================================\n";
    std::cout << " Generated " << pairs.size() << " pairs in "
              << total_ms << "ms\n";
    std::cout << " Avg per pair: "
              << (total_ms / args.count) << "ms\n";
    std::cout << "========================================\n\n";

    // Build and write JSON
    std::string json = BuildJson(pairs, args.bits, args.seed);

    try {
        // Ensure output directory exists
        std::string dir = utils::FileUtils::ParentDir(args.output);
        if (!dir.empty()) {
            utils::FileUtils::MkdirRecursive(dir);
        }
        utils::FileUtils::WriteTextFile(args.output, json);
        std::cout << " JSON written to: " << args.output << "\n";
        std::cout << " File size: "
                  << utils::FileUtils::FileSizeBytes(args.output)
                  << " bytes\n\n";
    } catch (const std::exception& ex) {
        std::cerr << "ERROR writing JSON: " << ex.what() << "\n";
        return EXIT_FAILURE;
    }

    // Quick sanity reload
    std::cout << " Verifying JSON reload...\n";
    try {
        std::string reloaded = utils::FileUtils::ReadTextFile(args.output);
        // Count pair entries
        std::size_t count = 0;
        std::size_t pos   = 0;
        while ((pos = reloaded.find("\"index\"", pos)) != std::string::npos) {
            ++count;
            ++pos;
        }
        std::cout << " Reloaded " << count << " pairs from JSON\n";
        if (count != static_cast<std::size_t>(args.count)) {
            std::cerr << "ERROR: count mismatch!\n";
            return EXIT_FAILURE;
        }
    } catch (const std::exception& ex) {
        std::cerr << "ERROR reloading JSON: " << ex.what() << "\n";
        return EXIT_FAILURE;
    }

    std::cout << "\n ALL " << args.count
              << " safe prime pairs verified and saved.\n";
    std::cout << "========================================\n";

    return EXIT_SUCCESS;
}
