/**
 * tests/test_crypto_params.cc
 * Unit test for Phase 2 Module 14: JSON Crypto Parser
 *
 * COMPILE:
 *   g++-13 -std=c++20 -Wall -Wextra -pthread \
 *       -I. -I./utils -I./crypto -I/usr/include \
 *       tests/test_crypto_params.cc \
 *       utils/uav-error.cc \
 *       utils/uav-enum-strings.cc \
 *       utils/uav-time-utils.cc \
 *       utils/uav-string-utils.cc \
 *       utils/uav-byte-utils.cc \
 *       utils/uav-math-utils.cc \
 *       utils/uav-file-utils.cc \
 *       utils/uav-log-level.cc \
 *       utils/uav-log-sink.cc \
 *       utils/uav-logger.cc \
 *       utils/uav-csv-logger.cc \
 *       crypto/uav-openssl-rand.cc \
 *       crypto/uav-openssl-ctx.cc \
 *       crypto/uav-bigint.cc \
 *       crypto/uav-aes.cc \
 *       crypto/uav-crypto-params.cc \
 *       -lssl -lcrypto \
 *       -o tests/test_crypto_params
 *
 * RUN:
 *   ./tests/test_crypto_params
 *
 * NOTE: Requires json/crypto_params.json generated by Module 13.
 *       Run: python3 scripts/gen_crypto.py first.
 */

#include "crypto/uav-crypto-params.h"
#include "crypto/uav-openssl-ctx.h"
#include "utils/uav-logger.h"
#include "utils/uav-string-utils.h"
#include "utils/uav-byte-utils.h"
#include "utils/uav-file-utils.h"

#include <cstdlib>
#include <iostream>
#include <string>
#include <fstream>

using namespace uav;
using namespace uav::crypto;

namespace {

int g_pass = 0;
int g_fail = 0;

#define ASSERT_TRUE(expr) \
    do { if (!(expr)) { \
        std::cerr << "  ASSERT_TRUE failed: " #expr \
                  << " @ line " << __LINE__ << "\n"; \
        return false; } } while (0)

#define ASSERT_EQ(a, b) \
    do { if (!((a) == (b))) { \
        std::cerr << "  ASSERT_EQ failed: " #a " != " #b \
                  << " @ line " << __LINE__ << "\n"; \
        return false; } } while (0)

#define ASSERT_THROWS(expr) \
    do { bool threw = false; \
        try { expr; } catch (...) { threw = true; } \
        if (!threw) { \
            std::cerr << "  ASSERT_THROWS failed: " #expr \
                      << " @ line " << __LINE__ << "\n"; \
            return false; } } while (0)

void RunTest(const std::string& name, bool (*fn)()) {
    std::cout << "[ RUN  ] " << name << "\n";
    bool ok = false;
    try { ok = fn(); }
    catch (const std::exception& ex) {
        std::cerr << "  Exception: " << ex.what() << "\n";
        ok = false;
    }
    if (ok) { std::cout << "[ PASS ] " << name << "\n\n"; ++g_pass; }
    else    { std::cout << "[ FAIL ] " << name << "\n\n"; ++g_fail; }
}

// ===========================================================================
// Test 1: Load from file
// ===========================================================================
bool test_load_from_file() {
    const std::string path = "json/crypto_params.json";

    // Check file exists first
    std::ifstream f(path);
    if (!f.good()) {
        std::cerr << "  SKIP: " << path << " not found.\n";
        std::cerr << "  Run: python3 scripts/gen_crypto.py first\n";
        return true;  // not a failure — just not generated yet
    }
    f.close();

    auto params = CryptoParamsLoader::LoadFromFile(path);

    ASSERT_EQ(params.scheme,           std::string("MKE-MGKM"));
    ASSERT_EQ(params.num_clusters,     3u);
    ASSERT_EQ(params.uavs_per_cluster, 6u);
    ASSERT_EQ(params.total_uavs,       18u);
    ASSERT_EQ(params.clusters.size(),  3u);

    std::cout << "  Scheme: " << params.scheme << "\n";
    std::cout << "  Clusters: " << params.num_clusters << "\n";
    std::cout << "  UAVs: " << params.total_uavs << "\n";
    return true;
}

// ===========================================================================
// Test 2: Cluster structure
// ===========================================================================
bool test_cluster_structure() {
    const std::string path = "json/crypto_params.json";
    std::ifstream f(path);
    if (!f.good()) {
        std::cout << "  SKIP: json/crypto_params.json not found\n";
        return true;
    }
    f.close();

    auto params = CryptoParamsLoader::LoadFromFile(path);

    for (utils::u32 c = 0; c < params.num_clusters; ++c) {
        const auto* cluster = params.GetCluster(c);
        ASSERT_TRUE(cluster != nullptr);
        ASSERT_EQ(cluster->cluster_id,    c);
        ASSERT_EQ(cluster->skdc_id,       c);
        ASSERT_EQ(cluster->num_uavs,      6u);
        ASSERT_EQ(cluster->slave_keys.size(), 6u);
        ASSERT_EQ(cluster->user_indices.size(), 6u);
        ASSERT_TRUE(cluster->eM   > BigInt(0));
        ASSERT_TRUE(cluster->MT_K > BigInt(0));
        ASSERT_TRUE(cluster->tek_int    > BigInt(0));
        ASSERT_EQ(cluster->tek_hex.size(), 64u);
        ASSERT_EQ(cluster->tek.size(),     32u);

        std::cout << "  Cluster " << c << ":\n";
        std::cout << "    eM   = "
                  << BigIntOps::ToDecString(cluster->eM).substr(0,30)
                  << "...\n";
        std::cout << "    MT_K = "
                  << BigIntOps::ToDecString(cluster->MT_K).substr(0,30)
                  << "...\n";
        std::cout << "    TEK  = "
                  << cluster->tek_hex.substr(0,20) << "...\n";
    }
    return true;
}

// ===========================================================================
// Test 3: Slave key structure
// ===========================================================================
bool test_slave_key_structure() {
    const std::string path = "json/crypto_params.json";
    std::ifstream f(path);
    if (!f.good()) {
        std::cout << "  SKIP: json/crypto_params.json not found\n";
        return true;
    }
    f.close();

    auto params = CryptoParamsLoader::LoadFromFile(path);

    for (utils::u32 c = 0; c < params.num_clusters; ++c) {
        const auto* cluster = params.GetCluster(c);
        ASSERT_TRUE(cluster != nullptr);

        for (const auto& sk : cluster->slave_keys) {
            // All fields must be positive
            ASSERT_TRUE(sk.e_i  > BigInt(0));
            ASSERT_TRUE(sk.d_i  > BigInt(0));
            ASSERT_TRUE(sk.n_i  > BigInt(0));
            ASSERT_TRUE(sk.x_i  > BigInt(0));
            ASSERT_TRUE(sk.y_i  > BigInt(0));
            ASSERT_TRUE(sk.Mi   > BigInt(0));
            ASSERT_TRUE(sk.Ni   > BigInt(0));
            ASSERT_TRUE(sk.xy_i > BigInt(0));
            ASSERT_TRUE(sk.p_i  > BigInt(0));
            ASSERT_TRUE(sk.q_i  > BigInt(0));

            // xy_i == x_i * y_i
            ASSERT_EQ(sk.xy_i, sk.x_i * sk.y_i);

            // e_i ≡ 1 mod 4
            ASSERT_EQ(BigIntOps::Mod(sk.e_i, BigInt(4)),
                      BigInt(1));
        }
    }

    std::cout << "  All slave keys: positive fields PASS\n";
    std::cout << "  xy_i == x_i * y_i: PASS\n";
    std::cout << "  e_i ≡ 1 mod 4: PASS\n";
    return true;
}

// ===========================================================================
// Test 4: Slave decryption property verification
// ===========================================================================
bool test_slave_decryption_property() {
    const std::string path = "json/crypto_params.json";
    std::ifstream f(path);
    if (!f.good()) {
        std::cout << "  SKIP: json/crypto_params.json not found\n";
        return true;
    }
    f.close();

    auto params = CryptoParamsLoader::LoadFromFile(path);

    int verified = 0;
    // Verify first slave in each cluster
    for (utils::u32 c = 0; c < params.num_clusters; ++c) {
        const auto* cluster = params.GetCluster(c);
        ASSERT_TRUE(!cluster->slave_keys.empty());

        const auto& sk = cluster->slave_keys[0];

        // d_i = e_i^(2*(x_i-1)*(y_i-1)-1) mod 4*x_i*y_i
        BigInt mod4xy  = 4 * sk.x_i * sk.y_i;
        BigInt exp_val = 2 * (sk.x_i - 1) * (sk.y_i - 1) - 1;
        BigInt expected = BigIntOps::ModPow(sk.e_i, exp_val, mod4xy);
        ASSERT_EQ(sk.d_i, expected);

        std::cout << "  Cluster " << c
                  << " UAV 0: d_i property VERIFIED\n";
        ++verified;
    }

    ASSERT_EQ(verified, 3);
    return true;
}

// ===========================================================================
// Test 5: MT_K slave decryption (main security property)
// pow(MT_K, d_i, n_i) == T mod n_i  for each UAV in cluster
// ===========================================================================
bool test_mtk_slave_decryption() {
    const std::string path = "json/crypto_params.json";
    std::ifstream f(path);
    if (!f.good()) {
        std::cout << "  SKIP: json/crypto_params.json not found\n";
        return true;
    }
    f.close();

    auto params = CryptoParamsLoader::LoadFromFile(path);

    int total_pass = 0;
    int total_fail = 0;

    for (utils::u32 c = 0; c < params.num_clusters; ++c) {
        const auto* cluster = params.GetCluster(c);
        ASSERT_TRUE(cluster != nullptr);

        const BigInt& MT_K = cluster->MT_K;
        const BigInt& T    = cluster->tek_int;

        for (const auto& sk : cluster->slave_keys) {
            // Core security property:
            // pow(MT_K, d_i, n_i) == T mod n_i
            BigInt recovered = BigIntOps::ModPow(
                MT_K, sk.d_i, sk.n_i);
            BigInt T_mod = BigIntOps::Mod(T, sk.n_i);

            bool ok = (recovered == T_mod);
            if (ok) {
                ++total_pass;
                std::cout << "  Cluster " << c
                          << " UAV " << sk.uav_id
                          << ": MT_K decrypt OK\n";
            } else {
                ++total_fail;
                std::cerr << "  Cluster " << c
                          << " UAV " << sk.uav_id
                          << ": MT_K decrypt FAILED\n";
            }
        }
    }

    std::cout << "  Total: " << total_pass << " pass, "
              << total_fail << " fail\n";

    ASSERT_EQ(total_fail, 0);
    ASSERT_EQ(total_pass, 18);
    return true;
}

// ===========================================================================
// Test 6: Lookup functions
// ===========================================================================
bool test_lookup_functions() {
    const std::string path = "json/crypto_params.json";
    std::ifstream f(path);
    if (!f.good()) {
        std::cout << "  SKIP: json/crypto_params.json not found\n";
        return true;
    }
    f.close();

    auto params = CryptoParamsLoader::LoadFromFile(path);

    // GetCluster
    const auto* c0 = params.GetCluster(0);
    const auto* c1 = params.GetCluster(1);
    const auto* c2 = params.GetCluster(2);
    ASSERT_TRUE(c0 != nullptr);
    ASSERT_TRUE(c1 != nullptr);
    ASSERT_TRUE(c2 != nullptr);
    ASSERT_TRUE(params.GetCluster(99) == nullptr);

    // GetSlaveKey within cluster
    const auto* sk0 = c0->GetSlaveKey(0);
    const auto* sk5 = c0->GetSlaveKey(5);
    ASSERT_TRUE(sk0 != nullptr);
    ASSERT_TRUE(sk5 != nullptr);
    ASSERT_TRUE(c0->GetSlaveKey(99) == nullptr);

    // GetSlaveKeyByUavId (global)
    // UAV 0-5 in cluster 0, 6-11 in cluster 1, 12-17 in cluster 2
    const auto* uav0  = params.GetSlaveKeyByUavId(0);
    const auto* uav6  = params.GetSlaveKeyByUavId(6);
    const auto* uav17 = params.GetSlaveKeyByUavId(17);
    ASSERT_TRUE(uav0  != nullptr);
    ASSERT_TRUE(uav6  != nullptr);
    ASSERT_TRUE(uav17 != nullptr);
    ASSERT_TRUE(params.GetSlaveKeyByUavId(99) == nullptr);

    ASSERT_EQ(uav0->uav_id,   0u);
    ASSERT_EQ(uav6->uav_id,   6u);
    ASSERT_EQ(uav17->uav_id, 17u);

    std::cout << "  GetCluster(0,1,2): PASS\n";
    std::cout << "  GetSlaveKey(0,5): PASS\n";
    std::cout << "  GetSlaveKeyByUavId(0,6,17): PASS\n";
    std::cout << "  Not-found returns nullptr: PASS\n";
    return true;
}

// ===========================================================================
// Test 7: TEK hex to bytes
// ===========================================================================
bool test_tek_bytes() {
    const std::string path = "json/crypto_params.json";
    std::ifstream f(path);
    if (!f.good()) {
        std::cout << "  SKIP: json/crypto_params.json not found\n";
        return true;
    }
    f.close();

    auto params = CryptoParamsLoader::LoadFromFile(path);

    for (utils::u32 c = 0; c < params.num_clusters; ++c) {
        const auto* cluster = params.GetCluster(c);

        // TEK must be 32 bytes
        ASSERT_EQ(cluster->tek.size(), 32u);

        // TEK hex must match TEK bytes
        std::string reconstructed;
        for (utils::u8 b : cluster->tek) {
            char buf[3];
            std::snprintf(buf, sizeof(buf), "%02x", b);
            reconstructed += buf;
        }
        ASSERT_EQ(reconstructed, cluster->tek_hex);

        std::cout << "  Cluster " << c
                  << " TEK: " << cluster->tek_hex.substr(0, 16)
                  << "...\n";
    }
    return true;
}

// ===========================================================================
// Test 8: Error on missing file
// ===========================================================================
bool test_missing_file_error() {
    ASSERT_THROWS(
        CryptoParamsLoader::LoadFromFile(
            "json/nonexistent_file.json"));
    std::cout << "  Missing file throws ConfigException: PASS\n";
    return true;
}

// ===========================================================================
// Test 9: Error on malformed JSON
// ===========================================================================
bool test_malformed_json_error() {
    ASSERT_THROWS(
        CryptoParamsLoader::LoadFromString(
            "{ invalid json }"));
    std::cout << "  Malformed JSON throws: PASS\n";
    return true;
}

// ===========================================================================
// Test 10: Validate counts
// ===========================================================================
bool test_validate_counts() {
    const std::string path = "json/crypto_params.json";
    std::ifstream f(path);
    if (!f.good()) {
        std::cout << "  SKIP: json/crypto_params.json not found\n";
        return true;
    }
    f.close();

    auto params = CryptoParamsLoader::LoadFromFile(path);

    // Count total slaves
    utils::u32 total_slaves = 0;
    for (const auto& c : params.clusters) {
        total_slaves += static_cast<utils::u32>(
            c.slave_keys.size());
    }

    ASSERT_EQ(total_slaves,      params.total_uavs);
    ASSERT_EQ(params.total_uavs, 18u);

    std::cout << "  Total slaves: " << total_slaves << "\n";
    std::cout << "  Matches total_uavs: PASS\n";
    return true;
}

} // anonymous namespace

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main() {
    std::cout << "====================================================\n";
    std::cout << "Phase 2 Module 14 — JSON Crypto Parser\n";
    std::cout << "UAV Secure FANET / NS-3.43\n";
    std::cout << "====================================================\n\n";

    log::Logger::Instance().Initialize(
        "/tmp/uav_crypto_params_logs",
        log::LogLevel::WARN,
        false);

    OpenSSLInit::Bootstrap();

    RunTest("load_from_file",               test_load_from_file);
    RunTest("cluster_structure",            test_cluster_structure);
    RunTest("slave_key_structure",          test_slave_key_structure);
    RunTest("slave_decryption_property",    test_slave_decryption_property);
    RunTest("mtk_slave_decryption",         test_mtk_slave_decryption);
    RunTest("lookup_functions",             test_lookup_functions);
    RunTest("tek_bytes",                    test_tek_bytes);
    RunTest("missing_file_error",           test_missing_file_error);
    RunTest("malformed_json_error",         test_malformed_json_error);
    RunTest("validate_counts",              test_validate_counts);

    std::cout << "====================================================\n";
    std::cout << "Results: " << g_pass << " passed, "
              << g_fail << " failed\n";
    std::cout << "====================================================\n";

    return (g_fail == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
}