/**
 * crypto/uav-crypto-params.h
 *
 * Data structures and JSON loader for crypto_params.json
 * generated by Module 13 (scripts/gen_crypto.py).
 *
 * JSON STRUCTURE:
 *   {
 *     "scheme": "MKE-MGKM",
 *     "num_clusters": 3,
 *     "uavs_per_cluster": 6,
 *     "total_uavs": 18,
 *     "clusters": [
 *       {
 *         "cluster_id": 0,
 *         "skdc_id": 0,
 *         "eM": "...",
 *         "n_total": "...",
 *         "tek_hex": "...",
 *         "T": "...",
 *         "MT_K": "...",
 *         "e_MK": "...",
 *         "user_indices": [0,1,2,3,4,5],
 *         "slave_keys": [
 *           {
 *             "uav_index": 0,
 *             "uav_id": 0,
 *             "e_i": "...",
 *             "d_i": "...",
 *             "n_i": "...",
 *             "x_i": "...",
 *             "y_i": "...",
 *             "Mi": "...",
 *             "Ni": "...",
 *             "xy_i": "...",
 *             "p_i": "...",
 *             "q_i": "..."
 *           }
 *         ]
 *       }
 *     ]
 *   }
 */

#ifndef UAV_CRYPTO_PARAMS_H
#define UAV_CRYPTO_PARAMS_H

#include "uav-types.h"
#include "uav-error.h"
#include "uav-bigint.h"
#include "uav-aes.h"

#include <string>
#include <vector>
#include <memory>

namespace uav {
namespace crypto {

// ===========================================================================
// SlaveKeyEntry — per-UAV slave decryption key parameters
// Loaded from slave_keys[] array in JSON
// ===========================================================================
struct SlaveKeyEntry {
    utils::u32  uav_index;    // index within cluster (0..N-1)
    utils::u32  uav_id;       // global UAV id (0..17)

    // MKE-MGKM slave parameters (all BigInt)
    BigInt      e_i;          // slave public exponent
    BigInt      d_i;          // slave decryption exponent
    BigInt      n_i;          // slave modulus (p_i * q_i)
    BigInt      x_i;          // (p_i - 1) / 2
    BigInt      y_i;          // (q_i - 1) / 2
    BigInt      Mi;           // CRT basis: n_total / (x_i * y_i)
    BigInt      Ni;           // CRT coefficient: Mi^-1 mod (x_i*y_i)
    BigInt      xy_i;         // x_i * y_i
    BigInt      p_i;          // safe prime p
    BigInt      q_i;          // safe prime q

    /// Verify internal consistency: xy_i == x_i * y_i
    bool Validate() const;

    /// Verify slave decryption property:
    /// d_i == e_i^(2*(x_i-1)*(y_i-1)-1) mod 4*x_i*y_i
    bool VerifyDecryptionProperty() const;
};

// ===========================================================================
// ClusterCryptoEntry — per-cluster master crypto parameters
// Loaded from clusters[] array in JSON
// ===========================================================================
struct ClusterCryptoEntry {
    utils::u32  cluster_id;
    utils::u32  skdc_id;
    utils::u32  num_uavs;

    // Master key (Algorithm 1 output)
    BigInt      eM;           // master public exponent
    BigInt      n_total;      // product of all x_i * y_i
    BigInt      N_global;     // product of all p_i * q_i
    BigInt      N_group;      // product of n_i for group members

    // Traffic Encryption Key
    AesGcmKey   tek;          // 32-byte AES-256 TEK
    std::string tek_hex;      // hex string for logging

    // Token (Algorithm 2 output)
    BigInt      tek_int;      // TEK as BigInt for MT_K computation (for MT_K construction)
    BigInt      MT_K;         // master token: e_MK + T
    BigInt      e_MK;         // master token exponent

    // Active user set
    std::vector<utils::u32> user_indices;

    // Per-UAV slave keys
    std::vector<SlaveKeyEntry> slave_keys;

    /// Get slave key for a specific UAV index within cluster.
    /// Returns nullptr if not found.
    const SlaveKeyEntry* GetSlaveKey(utils::u32 uav_index) const;

    /// Get slave key by global UAV id.
    const SlaveKeyEntry* GetSlaveKeyById(utils::u32 uav_id) const;

    /// Validate all slave keys.
    bool Validate() const;
};

// ===========================================================================
// CryptoParamsFile — top-level container
// Loaded from crypto_params.json
// ===========================================================================
struct CryptoParamsFile {
    std::string  scheme;             // "MKE-MGKM"
    std::string  global_key_hex;     // GK: 64 hex chars (32 bytes AES-256)
    utils::u32   num_clusters;
    utils::u32   uavs_per_cluster;
    utils::u32   total_uavs;
    utils::u32   seed;

    std::vector<ClusterCryptoEntry> clusters;

    /// Get cluster by cluster_id.
    /// Returns nullptr if not found.
    const ClusterCryptoEntry* GetCluster(
        utils::u32 cluster_id) const;

    /// Get slave key by global uav_id (searches all clusters).
    const SlaveKeyEntry* GetSlaveKeyByUavId(
        utils::u32 uav_id) const;

    /// Validate the entire loaded structure.
    bool Validate() const;
};

// ===========================================================================
// CryptoParamsLoader — loads JSON into CryptoParamsFile
// ===========================================================================
class CryptoParamsLoader {
public:
    /// Load crypto_params.json from file path.
    /// Throws ConfigException on parse error.
    /// Throws CryptoException on validation failure.
    static CryptoParamsFile LoadFromFile(
        const std::string& path);

    /// Load from JSON string (for testing).
    static CryptoParamsFile LoadFromString(
        const std::string& json_str);

    /// Validate loaded params and throw on error.
    static void ValidateOrThrow(const CryptoParamsFile& params);

private:
    static CryptoParamsFile ParseJson(const std::string& json_str);
    static ClusterCryptoEntry ParseCluster(
        const std::string& cluster_json);
    static SlaveKeyEntry ParseSlaveKey(
        const std::string& slave_json);

    /// Convert hex string to AesGcmKey (32 bytes).
    static AesGcmKey HexToAesKey(const std::string& hex);

    /// Simple JSON field extractor (no external dependency).
    static std::string ExtractString(
        const std::string& json,
        const std::string& key);

    static utils::u32 ExtractU32(
        const std::string& json,
        const std::string& key);

    static std::vector<utils::u32> ExtractU32Array(
        const std::string& json,
        const std::string& key);

    static std::vector<std::string> ExtractObjectArray(
        const std::string& json,
        const std::string& key);

    static BigInt ExtractBigInt(
        const std::string& json,
        const std::string& key);
};

} // namespace crypto
} // namespace uav

#endif // UAV_CRYPTO_PARAMS_H